services:
  web:
    image: node:20-alpine3.17
    ports:
      - "8081:8080"
    depends_on:
      - db
    working_dir: /home/node/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=ostranking
      - DB_DATABASE=ostranking
      - DB_PASSWORD=secret
      - SESSION_SECRET="this_is_a_session_secret"
    volumes:
      - ./:/home/node/app
    command: sh -c "npm install && npm run develop"
  db:
    image: mariadb:11.3.2
    volumes:
      - db:/var/lib/mysql
      - ./sql/dbinit.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MARIADB_DATABASE=ostranking
      - MARIADB_USER=ostranking
      - MARIADB_PASSWORD=secret
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_INITDB_SKIP_TZINFO=1
    ports:
      - "3308:3306"

volumes:
  db:
    name: ostranking_db
