CREATE TABLE IF NOT EXISTS users(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name NVARCHAR(32) NOT NULL, password_hash VARCHAR(60) NOT NULL, email VARCHAR(320) NOT NULL, creation_date DATETIME NOT NULL, privilege SMALLINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS shows(id INT NOT NULL PRIMARY KEY, name NVARCHAR(2048));
CREATE TABLE IF NOT EXISTS authors(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(64));
CREATE TABLE IF NOT EXISTS tags(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(64));
CREATE TABLE IF NOT EXISTS sources(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name NVARCHAR(128));
CREATE TABLE IF NOT EXISTS osts(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name NVARCHAR(256) NOT NULL, url VARCHAR(256) NOT NULL, length SMALLINT NOT NULL, creation_date DATETIME NOT NULL, update_date DATETIME NOT NULL, published_date DATE, short_length SMALLINT, alternate_name NVARCHAR(256));
CREATE TABLE IF NOT EXISTS author_ost(author_id INT NOT NULL, ost_id INT NOT NULL, role VARCHAR(32) NOT NULL, FOREIGN KEY (author_id) REFERENCES authors(id), FOREIGN KEY (ost_id) REFERENCES osts(id));
CREATE TABLE IF NOT EXISTS show_ost(show_id INT NOT NULL, ost_id INT NOT NULL, type SMALLINT NOT NULL, num SMALLINT NOT NULL, FOREIGN KEY (show_id) REFERENCES shows(id), FOREIGN KEY (ost_id) REFERENCES osts(id));
CREATE TABLE IF NOT EXISTS tag_ost(tag_id INT NOT NULL, ost_id INT NOT NULL, FOREIGN KEY (tag_id) REFERENCES tags(id), FOREIGN KEY (ost_id) REFERENCES osts(id));
CREATE TABLE IF NOT EXISTS source_ost(source_id INT NOT NULL, ost_id INT NOT NULL, FOREIGN KEY (source_id) REFERENCES sources(id), FOREIGN KEY (ost_id) REFERENCES osts(id))
CREATE TABLE IF NOT EXISTS scores(user_id INT NOT NULL, ost_id INT NOT NULL, score SMALLINT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (ost_id) REFERENCES osts(id));